import './globals.css';
import { overpass } from './fonts';
export const metadata = {
  title: 'Blogr landing page',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={overpass.className + ' bg-neutral-50 min-h-screen'}>{children}</body>
    </html>
  );
}
